providers = ["node"]

[phases.install]
cmds = [
  "npm install -g corepack",
  "corepack enable",
  "corepack prepare pnpm@9.1.0 --activate",
  "pnpm install --prod"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[phases.start]
cmds = [
  "pnpm run start"
]
